groups:
- name: dotnetcore-demo-build
  jobs:
  - build

resources:
- name: git
  type: git
  source:
    uri: https://github.com/jaymickey/todo-dotnetcore.git
    branch: master

jobs:
- name: build
  public: true
  plan:
  - get: git
    trigger: true
  - task: build
    file: git/ci/tasks/build/build.yml